### ISSUE TITLE
网络结构配置规则

### ISSUE THREAD

**Issue by cauivy** [yu-rp/KANbeFair#12]
请问在对比曲线中，每一个实验点对应KAN 和 MLP网络的参数配置是怎么制定的呢？您在文章提供了两个网络的一些候选配置数值，在实际实验中，每个实验点是随机组合还是有一些配置规则呢？

**Comment by yu-rp** [comment]
@cauivy 您好，感谢您的提问。

以MNIST上 FLOPs 的实验为例，我们实验是这样进行的：

1. 划定不同超参数的取值集合。
2. 使用grid search， 在所有可能的超参数取值组合上进行实验。
3. 绘制 FLOPs v.s. accuracy 散点图。
4. 画出类似 上包络线 的折线，来描述各个 FLOPs 下的最优 Accuracy。

**Comment by cauivy** [comment]
谢谢回复！
