### ISSUE TITLE
Incorrect Link in Related Work Section

### ISSUE THREAD

**Issue by Linsonng** [yu-rp/KANbeFair#2]
Hi, it seems there is an incorrect link in the Related Work section of the paper. In Part 6, the paper states:

"...merging KAN with GNN for graph-related tasks [13]", but the link incorrectly points to:

"[13] Chenxin Li, Xinyu Liu, Wuyang Li, Cheng Wang, Hengyu Liu, and Yixuan Yuan. U-kan makes strong backbone for medical image segmentation and generation, 2024."

Could you please verify the correct source for this statement and update the link accordingly?

Thanks for your attention on this.

**Comment by yu-rp** [comment]
Thank you for pointing out.

It should link to "GraphKAN: Enhancing Feature Extraction with Graph Kolmogorov Arnold Networks". We have corrected this typo and will update in the next arXiv version.

**Comment by Linsonng** [comment]
Perfect! Thanks for your great work!
