### ISSUE TITLE
增量学习那个地方，原文采用的是regression任务，在minist数据集上效果不好的原因可能是因为回归和分类任务的区别导致的么？

### ISSUE THREAD

**Issue by ElevenMorning** [yu-rp/KANbeFair#4]

**Comment by yu-rp** [comment]
@ElevenMorning 您好，感谢您的提问。

我们认为可能回归与分类并不是最主要的问题。

我们的一点思考是：KAN 在一维函数拟合任务中表现出更优异的增量学习能力，这主要归因于 Spline 激活函数具有扩展定义域的能力。这意味着当新的数据具有不同的取值范围时，Spline 函数能够在对先前任务性能影响较小的情况下，学习新的任务。然而，在 class-incremental 的设定下， MNIST 数据集根据数字的不同被划分为不同的任务，各任务的输入取值范围是相互重叠的。他们的取值范围都可以被认为是 $[0,255]^{28\times 28}$。我们认为，这种取值范围上的差异是导致结论不同的比较重要的原因。
