### ISSUE TITLE
The choice of Optimizer 

### ISSUE THREAD

**Issue by Murphyzc** [yu-rp/KANbeFair#5]
In the original paper, the author choose the refined LBFGS as the Optimizer. I also compared Adam with LBFGS, it usually showed that model with LBFGS performed better while it is slower than Adam.

I would like to know about the choice of optimizer could make the consequence of your paper a little different

**Comment by yu-rp** [comment]
Hi @Murphyzc , thank you for the issue.

We have included the code for the LBFGS optimizer by directly reusing the implementation from the original pykan repository. Below are some experimental results. The conclusions are generally consistent with those obtained using the Adam optimizer.

![lbfgs_parameters](https://github.com/user-attachments/assets/8227e41a-fca1-40c9-ada5-a3c4ff8298a8)

![lbfgs_flops](https://github.com/user-attachments/assets/ae912993-de6a-4257-b3dd-2af40424c4c2)

We also include a notebook that compares the training time between Adam and LBFGS.

**Comment by Murphyzc** [comment]
Thanks for your additional experiments!
