### ISSUE TITLE
No such file or directory: '../dataset/uciml_split_idx.pt'

### ISSUE THREAD

**Issue by DavidEnriqueNieves** [yu-rp/KANbeFair#7]
Apologies if its something obvious that I've missed, but I can't seem to find any way that the file `../dataset/uciml_split_idx.pt` can be loaded in from the existing script. My guess is that it was obtained from some official or unofficial splits, yet I can't find it in this repo, or in [this page](https://huggingface.co/papers/2407.16674). 

In the meantime, I'll simply be using a train test split just based off taking a certain percentage of the data:

```python3
def split_dataset(dataset):
    print("Splitting dataset...")

    split_path : Path = Path('../dataset/uciml_split_idx.pt')
    if split_path.exists():
        train_idx, test_idx = torch.load(str(split_path))
    else:
        train_test_perc : float = 0.8
        print(f"Using unofficial train test percentage of {train_test_perc}")
        train_idx, test_idx = torch.arange(0, round(len(dataset) * train_test_perc)), torch.arange(round(len(dataset) * train_test_perc), len(dataset))

    train_idx = torch.tensor(train_idx)
    test_idx = torch.tensor(test_idx)

    train_idx = train_idx[train_idx < len(dataset)]
    test_idx = test_idx[test_idx < len(dataset)]

    train_dataset = Subset(dataset, train_idx)
    test_dataset = Subset(dataset, test_idx)
    
    return train_dataset, test_dataset
```

It might not be the best way, but for now it'll have to do.

Could anyone let me know how this file is supposed to be obtained or generated?

**Comment by yu-rp** [comment]
Thank @DavidEnriqueNieves for the issue. 

We have uploaded the file `../dataset/uciml_split_idx.pt`. We used code very similar to yours to obtain the randomly split dataset. This file simply contains the index lists corresponding to these splits.
