### ISSUE TITLE
Question regarding MLP and KAN parameter count enforcement?

### ISSUE THREAD

**Issue by DavidEnriqueNieves** [yu-rp/KANbeFair#9]
Greetings,

By any chance, was any code developed to determine the appropriate number of hyperparameters in an MLP based off the hyperparameters of a KAN such that the parameters of both match?

I recognize that the answer can be solved by using the math in the paper, though I was wondering if you had a standard way of achieving this, since there might be more than one way of scaling up an MLP to match parameters with a KAN.

**Comment by yu-rp** [comment]
Hi @DavidEnriqueNieves ，

Thank you for your question. At present, we don't have a standardized method for "solving" the appropriate hyperparameters, as there can be many possible combinations, as you mentioned. Using the formulas provided in the paper to control other variables and solve for a specific one can be a practical approach.

If a highly precise result is not required or if you have some prior of the hyperparameters, you might also consider using our code to calculate the number of parameters and FLOPs. By generating several networks with different hyperparameters and directly comparing their number of parameters and FLOPs, you could identify a suitable hyperparameter combination.

**Comment by DavidEnriqueNieves** [comment]
> Hi @DavidEnriqueNieves ，
> 
> Thank you for your question. At present, we don't have a standardized method for "solving" the appropriate hyperparameters, as there can be many possible combinations, as you mentioned. Using the formulas provided in the paper to control other variables and solve for a specific one can be a practical approach.
> 
> If a highly precise result is not required or if you have some prior of the hyperparameters, you might also consider using our code to calculate the number of parameters and FLOPs. By generating several networks with different hyperparameters and directly comparing their number of parameters and FLOPs, you could identify a suitable hyperparameter combination.

Ok, that's fine by me. Thank you for your prompt reply.
